# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_bro_pb2 as hello__bro__pb2


class BroStub(object):
  """The bro service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/hellobro.Bro/SayHello',
        request_serializer=hello__bro__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__bro__pb2.HelloReply.FromString,
        )
    self.SayBye = channel.unary_unary(
        '/hellobro.Bro/SayBye',
        request_serializer=hello__bro__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__bro__pb2.HelloReply.FromString,
        )


class BroServicer(object):
  """The bro service definition.
  """

  def SayHello(self, request, context):
    """hello to somebody.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayBye(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BroServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=hello__bro__pb2.HelloRequest.FromString,
          response_serializer=hello__bro__pb2.HelloReply.SerializeToString,
      ),
      'SayBye': grpc.unary_unary_rpc_method_handler(
          servicer.SayBye,
          request_deserializer=hello__bro__pb2.HelloRequest.FromString,
          response_serializer=hello__bro__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hellobro.Bro', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
