# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_bro.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import validator_pb2 as validator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_bro.proto',
  package='hellobro',
  syntax='proto3',
  serialized_options=_b('\242\002\003HLW'),
  serialized_pb=_b('\n\x0fhello_bro.proto\x12\x08hellobro\x1a\x0fvalidator.proto\";\n\x0cHelloRequest\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\x9a\xe0\x1f\x02`\x01\x12\x15\n\x03\x61ge\x18\x02 \x01(\x05\x42\x08\x9a\xe0\x1f\x04\x10\x32\x18\x64\")\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02\x62y\x18\x02 \x01(\t2{\n\x03\x42ro\x12:\n\x08SayHello\x12\x16.hellobro.HelloRequest\x1a\x14.hellobro.HelloReply\"\x00\x12\x38\n\x06SayBye\x12\x16.hellobro.HelloRequest\x1a\x14.hellobro.HelloReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3')
  ,
  dependencies=[validator__pb2.DESCRIPTOR,])




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='hellobro.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hellobro.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\340\037\002`\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='hellobro.HelloRequest.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\232\340\037\004\0202\030d'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=105,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='hellobro.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hellobro.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='by', full_name='hellobro.HelloReply.by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'hello_bro_pb2'
  # @@protoc_insertion_point(class_scope:hellobro.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'hello_bro_pb2'
  # @@protoc_insertion_point(class_scope:hellobro.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)


DESCRIPTOR._options = None
_HELLOREQUEST.fields_by_name['name']._options = None
_HELLOREQUEST.fields_by_name['age']._options = None

_BRO = _descriptor.ServiceDescriptor(
  name='Bro',
  full_name='hellobro.Bro',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=150,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hellobro.Bro.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayBye',
    full_name='hellobro.Bro.SayBye',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRO)

DESCRIPTOR.services_by_name['Bro'] = _BRO

# @@protoc_insertion_point(module_scope)
